AbigailDawson/knownative

package-lock.json
package.json

This pull request is to resolve an issue where nodemon will not run unless it has been previously installed globally.
After this fix, when first setting up the project, nodemon will be installed automatically and can be used by running the script 'dev'.
Type `npm run dev` to start.

Set nodemon as dev dependency

---

src/demo/demo-components/DemoFlashcardForm/DemoFlashcardForm.css
src/demo/demo-components/DemoFlashcardForm/DemoFlashcardForm.jsx
src/demo/demo-components/DemoSavedWord/DemoSavedWord.css
src/demo/demo-components/DemoSavedWord/DemoSavedWord.jsx
src/demo/demo-components/DemoSavedWordsList/DemoSavedWordsList.css
src/demo/demo-components/DemoSavedWordsList/DemoSavedWordsList.jsx
src/demo/demo-pages/DemoTextPage/DemoTextPage.jsx

I created the sidebar that will display the demoflashcard activity form when you click on the appropriate button on the navBar. Moreover, I enabled it so that you can easily toggle the content in the sidebar in case you click on the "saved words" button while the sidebar is already present. I also created the "arrow back" button as requested for this issue. Lastly, I altered styling to more closely resemble the wireframe that was displayed. (I hard coded the colors. Let me know if you want me to add the colors to the CSS root!) 
Note: I pushed additional commits up since I was working on another issue, but didn't realize it may have tacked onto this pull request. The additional commits reflect completion of "Improve UI for Saved Words issue". In that, I was able to closely match the new …

Finished "Create sidebar for flashcard activity" issue (DEMO-23) [may also include commits for "Improve UI for Saved Words sidebar" issue]

---

src/demo/demo-components/DemoNav/DemoNav.css
src/demo/demo-components/DemoNav/DemoNav.jsx
src/index.js

Tooltips is restyled to use custom styling to match the theme of the website, while keeping the darker theme for readability.
Some notes:
- this was removed `import 'react-tooltip/dist/react-tooltip.css'`, since no longer using built-in styling from the library.
- Each tooltip icon is wrapped in a div for css specificity for custom styling, as suggested by the documentation.
- changing opacity affects hover animation. `delayShow={100}` helps keep it close to original animation

Restyle Tooltips

---

src/demo/demo-pages/DemoTextPage/DemoTextPage.jsx
src/index.css

Minor fix of a spacing issue with the buttons caused by the border on the GitHub button (hovering over buttons caused the image to wiggle). Removed border and changed to use `outline` instead.
Before:
https://github.com/user-attachments/assets/5770acc2-9602-47a3-b9b1-e61bc0d82f08
After:
https://github.com/user-attachments/assets/26ff7438-2d0c-4277-9145-1c2ccf6d9bc5
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmE3YWQzZTdmMDllZGM1NjA2MjIwMDMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QiLCJwcm9kdWN0SWQiOiIifQ.k24vnpjqXfR2luhSkxOHaC-R68RWaX2V3Lg5QVGlXC4">Huly&reg;: <b>GITHB-39</b></a></sub>

Fix minor spacing issue on GitHub button

---

src/demo/demo-components/DemoPopup/DemoPopup.css
src/demo/demo-components/DemoPopup/DemoPopup.jsx
src/demo/demo-components/DemoStudyText/DemoStudyText.jsx

User can now click outside the box and it will collapse, but also click seamlessly from one word to another without having to click 2 times. Instead of the fake triangle hack in CSS I created a square div with the same color as the Popup box and rotated it 45% to make it a triangle and then put a box shadow on it and used z-index to put it beneath the Popup box.
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmFkMWIyMTNmNGI3OTE2NjM0YmIzN2MiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QiLCJwcm9kdWN0SWQiOiIifQ.-BuN__Og-taeGI8pr0rBxIuwc9WIOE6KJdwc2LWljSE">Huly&reg;: <b>GITHB-48</b></a></sub>

Fixed Popup box triangle & handleOutsideClick.

---

src/components/Sentence/Sentence.css
src/demo/demo-components/DemoNav/DemoNav.css
src/demo/demo-components/DemoPopup/DemoPopup.css
src/demo/demo-components/DemoPopup/DemoPopup.jsx
src/demo/demo-components/DemoReadText/DemoReadText.css
src/demo/demo-components/DemoReadText/DemoReadText.jsx
src/demo/demo-components/DemoStudyText/DemoStudyText.css
src/demo/demo-components/DemoStudyText/DemoStudyText.jsx
src/demo/demo-components/DemoTranslateText/DemoTranslateText.css
src/demo/demo-components/DemoTranslation/DemoTranslation.css
src/demo/demo-components/DemoWord/DemoWord.css
src/demo/demo-pages/DemoTextPage/DemoTextPage.css
src/demo/demo-pages/DemoTextPage/DemoTextPage.jsx
src/index.css

This fixes the issue where text would resize too small when screen width became smaller. 
The main issue was `vmin` units were used for font-size. I decided to replace the `vmin` units for text sizes to `rem`, since `rem` was better for accesibility (uses user browser settings for example, if they need larger text).
Notes:
- since `rem` does not shrink when screen size gets smaller, I added media queries only where necessary, mainly used for the text size (I understand these could change when UX has mobile designs ready!)
- added a `max-width` of 900px on each tab container, so the text doesn't over extend
- switching from `vmin` units to `rem` units and applying `max-width` for the study tab text broke how the pop up was positioned. I added a `containerRef` to the text container so that …

Fixing page resize bug (DEMO-31)

---

src/components/LandingPageNav/LandingPageNav.jsx

Href change to line 12 of LandingPageNav.jsx to navigate to Github repo
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmIyMzA3MzMxNzgzMzIwZjc3ZTc1YWYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QiLCJwcm9kdWN0SWQiOiIifQ.YnT2w4KG8jngP_enFXMeCHAD7w94vRd0Op3hk3dS8t0">Huly&reg;: <b>GITHB-51</b></a></sub>

add github url to landing page nav bar

---

src/demo/demo-components/DemoNav/DemoNav.jsx

This fixes the error disableStyleInjection being on a react element. It was on a react element instead of a tooltip
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmI0YWQzYjljODhlY2NiNTBmYTVlYjEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QiLCJwcm9kdWN0SWQiOiIifQ.qjPAi1jhCkNgBWCQ0xhLBBd-vwWeKwPTb4gvuPuRCVk">Huly&reg;: <b>GITHB-57</b></a></sub>

Hotfix for disableStyleInjection console error

---

src/demo/demo-components/DemoPopup/DemoPopup.jsx

Popup box should now close out properly.

Added `ref={popupRef}` to return statement for DemoPopup component. 

---

src/demo/demo-components/DemoSavedWordsList/DemoSavedWordsList.css

Apply fix to isolate the scroll behavior to saved words instead of the entire page

DEMO-34 (Issue) - [Fix] Scrolling Saved Words scrolls the entire page

---

src/pages/LandingPage/LandingPage.css
src/pages/LandingPage/LandingPage.jsx

Created a warning modal that triggers when user clicks the "Demo" button  and the screen size is the same or smaller than 1366x1024 (basically the dimensions of an Ipad Pro). The user can then chose to continue anyway, navigating them to the demo or go back, exiting out of the modal and remaining on the landing page.  
https://huly.app/workbench/knownative/tracker/DEMO-40
There is a bug when the user uses the escape key, which I believe comes from how the base modal component handles key events. Should be adjusted when modal component is refactored. 
Screensize larger than 1366x1024:
> On landing page, click "Demo" Button
-Expected result: User is navigated to the Demo Page, no modal triggered.
Screensize same or smaller than 1366x1024:
>Inspect/Open web console
>Click "Toggle Device …

DEMO-40: Create warning modal for small screen users

---

src/demo/demo-components/DemoFlashcardForm/DemoFlashcardForm.jsx
src/demo/demo-components/DemoFlashcardGame/DemoFlashcardGame.css
src/demo/demo-components/DemoFlashcardGame/DemoFlashcardGame.jsx
src/demo/demo-pages/DemoTextPage/DemoTextPage.jsx

Created a new `DemoFlashcardGame` component to hold the logic and rendering of flashcard quiz and modal.
This new component now contains all of the state variables for the game, as well as update and logic functions. It renders as the "Start Quiz" button on the Flashcard Form sidebar component, and that button will change the 'open' state to show the Dialog. I fixed an issue I encountered where the "play again" button wasn't resetting the quiz, just causing the completion animation to replay. Other than that, everything about the game works the same and nothing has been changed other than the refactoring of components.
https://github.com/user-attachments/assets/11b563e9-07b8-4cdf-9c3e-4285328dc3ed

DEMO-45: Move flashcard game logic out of main text page file

---

public/index.html
src/demo/demo-components/DemoReadText/DemoReadText.css
src/demo/demo-components/DemoSentence/DemoSentence.css
src/demo/demo-components/DemoSentence/DemoSentence.jsx
src/demo/demo-components/DemoTranslateText/DemoTranslateText.css
src/demo/demo-components/DemoTranslation/DemoTranslation.css
src/demo/demo-components/DemoTranslation/DemoTranslation.jsx

This is updating the translation tab's UI, which includes: 
- replacing show/hide translation text with a google icon
- adding hover and selected styling/functionality to translate icon
- transition animation when user clicks the translate icon
- moved sentence translation into a useEffect so it can start translating on page render. It otherwise took some time for the text to load

DEMO-14: Improve UI for sentence translations

---

src/demo/demo-components/DemoReadText/DemoReadText.css

The demo header font size now scales with the paragraph font when zooming in/out.

Add header size scales with paragraph

---

src/demo/demo-components/DemoFlashcardForm/DemoFlashcardForm.jsx
src/demo/demo-components/DemoFlashcardGame/DemoFlashcardGame.jsx
src/demo/demo-pages/DemoTextPage/DemoTextPage.jsx

The text area will now blur when the flashcard quiz is active. This blur will apply whether on the read, study, or translate tab when opening the quiz. This seemed like the easiest solution to stop the user "cheating" by seeing answers in the background.
This was achieved by adding a `blurRef` to the text area and then creating an update function. The update function will add a blur filter to the component via inline staying when it receives `true` and will remove the in-line style when receiving `false`.  The update function is passed down to the game component. The `blurText` function was added to both the `startQuiz` and `handleClose` functions.
https://github.com/user-attachments/assets/04ed03d8-e362-4142-88cf-d7ab0fe075c6

DEMO-37: Hide Saved Words During Flashcard Activity

---

src/demo/demo-components/DemoPopup/DemoPopup.css
src/demo/demo-components/DemoPopup/DemoPopup.jsx
src/demo/demo-components/DemoStudyText/DemoStudyText.jsx

This fix prevents the ability to save the same word multiple times from the study tab.
I passed down the `checkSaved` function to the word popup in order to implement conditional rendering on the save button. Now, if a word has already been saved to the library, the user will see a check mark instead of the add button and will not be able to add the word to their saved terms again.
The check mark alternative element is still a button element, to facilitate an easy update in the future should we move to adding 'remove word' capabilities to the popup.
https://github.com/user-attachments/assets/e1219872-8402-44e7-96c5-caabfc3d0658

DEMO-48: [Fix] User can save the same word repeatedly

---

src/demo/demo-components/DemoSentence/DemoSentence.jsx
src/demo/demo-components/DemoTranslateText/DemoTranslateText.jsx

First text block on translation tab shows on page render.
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmQzMmQzZGQzNDkxNjA0YmIwZjk3OWUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QifQ.GgBQaKApdDc7Jj947grLIlkoNTgxKN4Matxk736FpE8">Huly&reg;: <b>GITHB-100</b></a></sub>

DEMO 50: Set first sentence to be open (translated) by default

---

src/demo/demo-pages/DemoTextPage/DemoTextPage.jsx

I noticed some things seemed a little scattered on the main text page, so I did some reorganizing. No functionality has been changed, but I moved some declarations around so that all related state values are grouped together and all related functions are grouped together. I also moved some old, commented-out code to the bottom of the file so that it wouldn't be cluttering up active code.
These changes improve readability, and will also make refactoring easier for the upcoming state management changes. Having all state values and functions grouped together will ensure that it's easy to extract all relevant code when the time comes.
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmQ2MjY0M2ZmMDBmMWVjN2RiZDZiYzEiLCJndWVzdCI6InRydWUiLC …

Organize DemoTextPage

---

src/demo/demo-components/DemoPreviewTextModal/DemoPreviewTextModal.jsx
src/demo/demo-pages/DemoTextPage/DemoTextPage.css
src/demo/demo-pages/DemoTextPage/DemoTextPage.jsx

Adds a simple link element next to the difficulty tag which dynamically links to the source of the currently loaded article. Includes an icon to indicate link will open in another tab.
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmRiOWE3NTNiYjU3YTg1ZThlZTVjNTkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QifQ.4K0tYFMRZXJZ5FIuy-NkCkRD3py4zinDo5-RZELlAzg">Huly&reg;: <b>GITHB-106</b></a></sub>

DEMO-51/DEMO-52: Add Link to Article Source

---

src/demo/demo-components/DemoFlashcardForm/DemoFlashcardForm.css
src/demo/demo-components/DemoFlashcardForm/DemoFlashcardForm.jsx
src/demo/demo-components/DemoFlashcardGame/DemoFlashcardGame.css
src/demo/demo-components/DemoFlashcardGame/DemoFlashcardGame.jsx

When no words in word list, "Start Quiz" button is disabled with opaque and gray styling. Also shows the same message when no words are in list as the Saved Words tab.
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmU4ZmRlNzQ5YzY4N2Y5NWNlOWY2NzQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QifQ.1hXuUM3iw0s6d4p9omvzUtV9F-p5mioZn38LnCw_LyA">Huly&reg;: <b>GITHB-115</b></a></sub>

DEMO-62: Disable flashcard activity when no words have been saved

---

src/demo/demo-components/DemoExitModal/DemoExitModal.css
src/demo/demo-components/DemoExitModal/DemoExitModal.jsx
src/demo/demo-pages/DemoTextPage/DemoTextPage.jsx

This PR refactors the exit demo modal to use the reusable modal component, making it consistent with the other two modals (screensize warning and edit word modal) 
Before:
After:
https://huly.app/workbench/knownative/tracker/DEMO-33
None
Demo Page:
> Click the exit button in the bottom left of the screen
> Verify the exit modal pops up
> Verify the "X" button closes the modal and remains on the demo page
> Verify hitting the ESC key closes the modal and remains on the demo page
> Verify clicking the "Go Back" button closes the modal and remains on the demo page
> Verify clicking the "Exit" button closes the modal and navigates to the landing page

DEMO-33: Refactoring the Exit Modal

---

client/src/App.jsx
client/src/KnowNativePage/AddTextPage/AddTextPage.jsx
client/src/KnowNativePage/AddTextPage/AddTextPage.scss
client/src/KnowNativePage/DashboardPage/DashboardPage.jsx

When users click on the dashboard button "+ Add Text", they'll be redirected to `AddTextPage.jsx` so that they can import a text using copy and paste.
The Import Text form allows the user to enter the following fields:
- Title
- Source
- Content.
The form will later need to be updated according to wireframe designs and future features such as tags and status.
* [`client/src/App.jsx`](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c67206aac23ddc9aR14): Imported `AddTextPage` and added a new route for it in the `App` component.
* [`client/src/KnowNativePage/AddTextPage/AddTextPage.jsx`](diffhunk://#diff-e0cc514d802ebed37cd7fdbe11ad4672c2a9d96591cf90d703644d9a3d59af5cR1-R180): Created the `AddTextPage` component.
* …

Add a Text Import Form

---

server/models/text.js

It worked!
After dropping the `title` index from the MongoDB collection and removing the `unique: true` property on `textSchema`, users can now import texts with existing titles.

Update textSchema to allow text imports with existing Titles

---

client/src/LandingPages/components/Forms/PasswordValidation.jsx
client/src/LandingPages/components/LandingPageSignupModal/SignupModal.jsx

As per the issue...
1. Upon entering page, password requirements are not visible.
2. When the user clicks on the password field, the password requirements pop up and are visible. The requirement text is in default gray/black.
3. The password requirements icons appear red until fulfilled, in which case they switch to green.
4. When a user begins typing in the “confirm password" field, a "confirm password" validation field stating "Passwords do not match" appears until the requirement is fulfilled. This field disappears when the password fields match.
https://github.com/user-attachments/assets/e58e90d8-2ed3-4f2b-a500-89cb9dfdc04a

SIGNUP #6: Implement Password Flow & Alter Password Design

---

client/src/services/authService.js

This PR fixes the bug which was preventing users from logging in. The issue came from how `authService.js` in the client was collecting the base URL for the API. It was requesting to the wrong port, so the solution was to fix how the base URL was defined.
To prioritize security, this PR requires a `.env` file be created at the root of the client directory. Inside, all one needs to do is make a `VITE_API_BASE_URL` variable which points to the correct port.
https://github.com/user-attachments/assets/d9bf98b9-76a0-49f8-91a3-8f3e374fe46a

Fix login bug
