- controllers/api/texts.js
- package.json
Also update proxy port in `package.json`
<sub><a href="https://huly.app/guest/knownative-663281db-87be16d699-2a6bdc?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjMzZDdhZTAyYzdiMjYwNDYzMzZhMmQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxZGItODdiZTE2ZDY5OS0yYTZiZGIiLCJwcm9kdWN0SWQiOiIifQ.mr7qehRDS1GPb6rQXSWJ4Ln0LUPxQzknsY00ODPKFXE">Huly&reg;: <b>KNOWN-17</b></a></sub>
> Fix issue with Google Translate API key

- controllers/api/demo.js
- routes/api/demo.js
- src/demo/demo-components/DemoSentence/DemoSentence.jsx
- src/utilities/demo-api.js
Refactored function to use new API, route & controller
<sub><a href="https://huly.app/guest/knownative-663281db-87be16d699-2a6bdc?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjMzZDllMTAyYzdiMjYwNDYzMzZhNTUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxZGItODdiZTE2ZDY5OS0yYTZiZGIiLCJwcm9kdWN0SWQiOiIifQ.zoZBuBhAotJ6sTnAcdzJUbDAhsRguZ87MF7Fg14Ahwk">Huly&reg;: <b>KNOWN-18</b></a></sub>
> Refactor demo translation functionality

- src/pages/AboutPage/AboutPage.css
- src/pages/AboutPage/AboutPage.jsx
- src/pages/App/App.jsx
- src/pages/AuthPage/AuthPage.jsx
* Added a temporary link to About page from landing page for convenience during development
* Renamed the About component to AboutPage, updated imports, and moved to src/pages directory
* Fixed styling on About page component (was applying styles to h3 and p tags globally, rather than scoped within the component)
<sub><a href="https://huly.app/guest/knownative-v2?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjQ0ZjM3ODEwYjdiODJiMTQ1MjJlOTkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtdi02NjNlNTE5Ni1mZDAxMWQyYWUxLTYwOWM1ZSIsInByb2R1Y3RJZCI6IiJ9.GYL5kwPCpFLEbTK5lBpNbg3-V9-QA2KfCgVChrTh5ts">Huly&reg;: <b>KNOWN-10</b></a></sub>
> Fixes to About page

- src/demo/demo-components/DemoSavedWord/DemoSavedWord.jsx
- src/demo/demo-components/DemoStudyText/DemoStudyText.jsx
- src/demo/demo-pages/DemoTextPage/DemoTextPage.jsx
- Refactor code for saving to localStorage
- Implement delete from savedWordsList for localStorage
- Implement edit for savedWordsList for LocalStorage
- Create a function to generate IDs locally (previously generated by database)
- Add Chinese characters to SavedWordsList
- Implement annotations for savedWords locally
- Implement flashcard game locally
> Implement all DemoTextPage features locally using localStorage

- src/demo/demo-components/DemoFlashcardForm/DemoFlashcardForm.css
- src/demo/demo-components/DemoFlashcardForm/DemoFlashcardForm.jsx
- src/demo/demo-components/DemoSavedWord/DemoSavedWord.css
- src/demo/demo-components/DemoSavedWord/DemoSavedWord.jsx
Hi Abigail. I fixed the blue text bug on demo flashcard form and centered the word meaning text in each saved card. Let me know if this works!
Also, I fixed the delete word issue (as the code stood before, you couldn't delete a word yet by pressing the delete button on a saved word).
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmE4NDA4YTdmMDllZGM1NjA2MjJhYjEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QiLCJwcm9kdWN0SWQiOiIifQ.N_FsZdTx-ujcohJEAR0dWh3TaMMKtZRdUV_xAHCam9s">Huly&reg;: <b>GITHB-41</b></a></sub>
> BUG FIXES: Fixed blue text bug on demo flashcard form and centered the word meaning text in each saved card.

- package-lock.json
- package.json
- src/demo/demo-components/DemoExitModal/DemoExitModal.jsx
- src/demo/demo-components/DemoNav/DemoNav.jsx
- src/demo/demo-pages/DemoTextPage/DemoTextPage.jsx
When a user clicks the exit demo icon, a warning will pop up asking them to confirm.
> add warning when exit icon is clicked

- package-lock.json
- package.json
- src/demo/demo-components/DemoPopup/DemoPopup.css
- src/demo/demo-components/DemoPopup/DemoPopup.jsx
- src/demo/demo-components/DemoStudyText/DemoStudyText.jsx
- src/demo/demo-components/DemoWord/DemoWord.css
- src/demo/demo-components/DemoWord/DemoWord.jsx
Added bold glyph to popup, changed box height depending on how many lines are in the 'meaning', added a MUI icon & used as an SVG to add a stroke to match the popup box shadow, enabled popup to open on click of consecutive words
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmFhYTcyZTA0Mzg2NzIxODQ0NzIyNWYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QiLCJwcm9kdWN0SWQiOiIifQ.My-faBSUpvhNi34RTGwpOdJIDY1wZmfo0SCSgp8-nrc">Huly&reg;: <b>GITHB-44</b></a></sub>
> Demo 13 Improve appearance and functionality of word popups

- src/components/LandingPageNav/LandingPageNav.jsx
- src/index.css
- src/pages/App/App.jsx
- src/pages/ContactPage/ContactPage.jsx
Created and routed contact page along with some styling to be a bit more on brand. Added social links too.
> Created Contact Page

- src/demo/demo-components/DemoExitModal/DemoExitModal.jsx
- src/demo/demo-components/DemoInfoSidebar/DemoInfoSidebar.css
- src/demo/demo-components/DemoInfoSidebar/DemoInfoSidebar.jsx
- src/demo/demo-components/DemoNav/DemoNav.jsx
- src/demo/demo-pages/DemoTextPage/DemoTextPage.jsx
The info sidebar can be opened and used to go to GitHub or back to the homepage
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmFkNTFmOTMxNzgzMzIwZjc3ZTRjNWIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QiLCJwcm9kdWN0SWQiOiIifQ.aZrn9FcTWW1C4r2HogZSFuCA44wnlLMISKoMO70sLzo">Huly&reg;: <b>GITHB-49</b></a></sub>
> Add info sidebar with Visit GitHub and Exit functionality

- src/components/LandingPageFooter/LandingPageFooter.css
- src/components/LandingPageFooter/LandingPageFooter.jsx
- src/components/LandingPageNav/LandingPageNav.jsx
- src/pages/AboutPage/AboutPage.css
- src/pages/AboutPage/AboutPage.jsx
- src/pages/App/App.jsx
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmI4MWNhZDg5YjIzNzNlMjY4ZWUyYWMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QiLCJwcm9kdWN0SWQiOiIifQ.A3M8OZd4Lg3Rk4KTsSIXXymhAVTLotPrz-xF1FZQsLk">Huly&reg;: <b>GITHB-59</b></a></sub>
> About page template

- src/demo/demo-components/DemoEditWordModal/DemoEditWordModal.jsx
- src/demo/demo-components/DemoLibrary/DemoLibrary.css
- src/demo/demo-components/DemoLibrary/DemoLibrary.jsx
- src/demo/demo-components/DemoNav/DemoNav.jsx
- src/demo/demo-pages/DemoTextPage/DemoTextPage.jsx
Hey! I just finished Demo 18 (initial creation of the sidebar for the Library). Let me know if it's good! I have the other library sidebar issues assigned to myself (demo 19, 20, 21, etc), and so I'll keep working on further fleshing out the library sidebar section within this new branch.
Also, in the Saved Words List edit modal, I made "term" (Chinese character) non-editable as we had talked about earlier.
> Completed Demo-18 (Create sidebar for Library)

- src/index.css
Apply fix to remove the gap between nav and sidebar
> DEMO-35 [Fix]

- src/demo/demo-components/DemoSavedWord/DemoSavedWord.css
- src/demo/demo-components/DemoSavedWordsList/DemoSavedWordsList.css
Apply fix to make edit and delete buttons visible
> DEMO-42 - [Fix]

- src/components/LandingPageNav/LandingPageNav.css
- src/components/LandingPageNav/LandingPageNav.jsx
Improve appearance of landing page nav links
> SITE-14 - [Improve]

- src/demo/demo-pages/DemoTextPage/DemoTextPage.jsx
Fixed the remaining count in the flashcards
> DEMO-41 (Issue) [Fix] Flashcard activity displays inaccurate correct/remaining count

- src/demo/demo-components/DemoFlashcardGame/DemoFlashcardGame.jsx
A small update, wrote a function to shuffle an array and then applied to the the flashcards array inside of the `getFlashcards` function. The flashcardsArray will now return in a random order each time a flashcard quiz is started or repeated.
> DEMO-56 Add Shuffle to Flashcards

- src/demo/demo-components/DemoChooseTextCard/DemoChooseTextCard.css
- src/demo/demo-components/DemoDifficultyTag/DemoDifficultyTag.css
- src/demo/demo-pages/DemoTextPage/DemoTextPage.css
- src/demo/demo-pages/DemoTextPage/DemoTextPage.jsx
- src/index.js
Fixed it! The border radius should be even now and there should be more space between the title and the difficulty tag. :)
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmNmNzM2MWZlYTI2MDgxMDA3MGZiYWUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QifQ.TZ8cgfxAWiCgtrhIQIPdrBot_ClrETca85EbQzUFrKU">Huly&reg;: <b>GITHB-94</b></a></sub>
> FINISH Demo 57- [Fix] Border radius on Library cards & spacing of level badge

- src/demo/demo-components/DemoPopup/DemoPopup.css
Fixed proportion of save button upon zoom in and out. There is still a visible issue upon zoom out 80% and less due to layout shift. Updated close button position to align with save button.
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmQ1YWVjZmZmMDBmMWVjN2RiOGQ5YjIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QifQ.c1NR7J4-S4-IfiXCteF3Sz80HnEfXnG3QGir5adnLoc">Huly&reg;: <b>GITHB-101</b></a></sub>
> Demo 36 save button proportion fix

- src/pages/AboutPage/AboutPage.css
- src/pages/AboutPage/AboutPage.jsx
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmJhODcxYzI3NDVhNTE5YTJjZmMyYmUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QiLCJwcm9kdWN0SWQiOiIifQ.dVzSiu5fFavwTTLa1RRZhxLdCL9wRIODzVxmazE2U7k">Huly&reg;: <b>GITHB-61</b></a></sub>
> add in css grid for core contributor and broiler language

- src/contexts/SavedWords/SavedWordsActions.js
Created action enum and functions for `SavedWords` state management actions to be used in reducer.
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmU4OWMyMzQ5YzY4N2Y5NWNlOGJhNmUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QifQ.CE_rWFerwr3SUe3Wjbudk49oaQEPCxGxzXHNJyYwg4M">Huly&reg;: <b>GITHB-113</b></a></sub>
> KN-12 Create SavedWords Actions

- src/contexts/SavedWords/SavedWordsReducer.js
Sets up state for `SavedWords` and creates a reducer to manage actions. Includes a helper function for updating saved words.
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmU4YmRlOTQ5YzY4N2Y5NWNlOTA1NzIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QifQ.8MWSXpM3c9iZeqK4LjhsZJabRhWpkBpBsjqqfZFrGOg">Huly&reg;: <b>GITHB-114</b></a></sub>
> KN-13 Saved Words Reducer

- src/pages/ContributePage/contributordata.js
Made sure all the social links are accurate and the descriptions are now grammatically correct.
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmVjOTQ5MTQ5YzY4N2Y5NWNmOTY5NTAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QifQ.yihLxtHsY8A32w1luKxpGrQWpIxIuBHb7XPtxO_noIo">Huly&reg;: <b>GITHB-122</b></a></sub>
> SITE-19 (Issue)

- src/contexts/SavedWords/SavedWordsProvider.jsx
- src/contexts/SavedWords/SavedWordsReducer.js
- src/contexts/Sidebar/SidebarActions.js
- src/contexts/Sidebar/SidebarProvider.jsx
- src/contexts/Sidebar/SidebarReducer.js
- src/demo/demo-pages/DemoTextPage/DemoTextPage.jsx
Fixed up stuff based on suggestions from my last PR:
1. Removed all comments
2. Wrote action.data vs action.payload
3. For error throwing, I wrote "Invalid Action:" + action.type as you suggested.
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZkOWY0MDQzYjBiYWU0OTViMDViZDUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QifQ.GMOSBWhLs7PHPTo_ILjjeO4KiXaN76GZ8v9DQAW-q7E">Huly&reg;: <b>GITHB-134</b></a></sub>
> Create sidebar action and reducer

- client/src/DemoPage/DemoMainContent/DemoStudyText/components/DemoWord/DemoWord.css
- client/src/LandingPages/LoginPage/LoginPage.css
- client/src/LandingPages/LoginPage/LoginPage.jsx
- server/controllers/api/userCtrl.js
Finished basic login #1 and #2 tasks. Works as expected. Styling to be fleshed out later.
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFlZWMxYjI3Y2M3NjgxYzYyMmU5YTMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QifQ.ZwMaR2JTAJwCiSW8bBk8ob9ixAMDIWtQRtvGhkY0eqQ">Huly&reg;: <b>GITHB-149</b></a></sub>
> Finished Login #1 and #2

- server/models/card.js
- server/models/deck.js
- server/models/tag.js
- server/models/text.js
#KN-39 Models/Schemas for Text, Card, Deck, Tag
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRiM2RlNmQyZWY0Y2JjYzQ2Y2MxZjUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QifQ.8mZpXqu5HpdZ-Oz9dEvq-le_lHMo_wRwknXMe7z72Gk">Huly&reg;: <b>GITHB-161</b></a></sub>
> Kn39 models

- client/src/LandingPages/SignupPage/SignupPage.jsx
- client/src/LandingPages/SignupPage/SignupPage.scss
Update to `SignupPage.jsx` component to improve user experience by conditionally rendering the password validation feedback and enhancing the layout to match the wireframe.
Enhancements to user experience:
* [`client/src/LandingPages/SignupPage/SignupPage.jsx`](diffhunk://#diff-82c37d531ed61059f66204eabdc088b5689c756b0ba82e8fb47aa06ad054256fR28): Added `isPasswordTyping` state to track when the user is typing in the password field, and updated the `handleChange` function to set this state. [[1]](diffhunk://#diff-82c37d531ed61059f66204eabdc088b5689c756b0ba82e8fb47aa06ad054256fR28) [[2]](diffhunk://#diff-82c37d531ed61059f66204eabdc088b5689c756b0ba82e8fb47aa06ad054256fR97-R99)
* [`client/src/LandingPages/SignupPage/SignupPage.jsx`](diffhunk://#diff-82c37d531ed61059f66204eabdc088b5689c756b0ba8 …
> Add Conditional Rendering for Password Validation Messages.

- client/src/DemoPage/DemoMainContent/DemoStudyText/DemoStudyText.jsx
- server/controllers/api/demo.js
- server/package-lock.json
- server/package.json
Merging what we did today Austin!
We were able to create an object with pinyin, charGroup, and meaning in server/controllers/api/demo.js! Check it out!
<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVhNTM2NjFlMDYzMmRkMDhlMzM2ZDciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QifQ.SI-DFr2RDWfE5mOecj7IB-Hab8wRdie8PWbDa5EPb8k">Huly&reg;: <b>GITHB-167</b></a></sub>
> Tokenization dec 11 2024

- client/src/KnowNativePage/AddTextPage/AddTextPage.jsx
- server/controllers/api/demo.js
- server/routes/api/demo.js
Connected to #181 
Continuing with the Text Import tasks, this pull request adds the necessary code to save an imported text to the database.
The most significant changes involve adding a new route and controller function on the server, and updating the client-side form submission logic.
* [`client/src/KnowNativePage/AddTextPage/AddTextPage.jsx`](diffhunk://#diff-e0cc514d802ebed37cd7fdbe11ad4672c2a9d96591cf90d703644d9a3d59af5cL26-R49): Updated the `handleSubmit` function to use the `sendRequest` utility function for sending form data to the `/api/demo/texts` endpoint.
* [`client/src/KnowNativePage/AddTextPage/AddTextPage.jsx`](diffhunk://#diff-e0cc514d802ebed37cd7fdbe11ad4672c2a9d96591cf90d703644d9a3d59af5cR6): Imported the `sendRequest` utility function.
* …
> Connect Import Text Form to the Backend

- server/controllers/api/textController.js
- server/routes/api/textRoutes.js
This PR includes only the delete code on the backend. It makes sure to delete the cards associated with the text through the textId, then deletes the actual text. (tested through Postman)
❗ Could not test if the card deletion worked, since I don't see anything set up yet for cards for a text (but if there is, let me know). 
Resolves #187
> delete functionality on backend only

- client/src/DemoPage/components/DemoWelcomeModal/DemoWelcomeModal.jsx
- client/src/ui-components/Radio/radio.jsx
- client/src/ui-components/Radio/radio.scss
This PR adds a reusable `Radio` component
Closes #192
> Create reusable radio button component

- client/.env.example
- client/src/KnowNativePage/AddTextPage/AddTextPage.jsx
- client/src/services/authService.js
- client/src/utilities/demo-api.js
- client/src/utilities/send-request.js
- client/src/utilities/texts-api.js
- client/src/utilities/words-api.js
- server/controllers/api/demo.js
- server/controllers/api/textController.js
- server/routes/api/demo.js
- server/routes/api/textRoutes.js
There is issue while login, sign up, and add text.
- as given variable in .env.example file, paste it to your .env file,  variable name is ''VITE_API_BASE_URL"
this variable is more secure way
> Fix/login-sign-up -add-text-issue & Organize addText  client & server code

- client/src/LandingPages/BlogPage/BlogPage.jsx
- client/src/LandingPages/components/LandingPageHeader/LandingPageNav.scss
- server/package-lock.json
- Added positioning styles to the navbar
- This resolves the issue mentioned in PR [#228](https://github.com/AbigailDawson/knownative/pull/228)
> Fix navbar issue on Blog and Contribute page

- client/src/ui-components/Vocab/vocab.jsx
- client/src/ui-components/Vocab/vocab.scss
This PR adds a reusable vocab card component
Closes #198  and #191
> Add vocab card component
